micronaut:
  application:
    name: appCliente
datasources:
  default:
    url: jdbc:mysql://localhost:3306/cdcm?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: '123456'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
